### ISSUE TITLE
You have not installed wrangler

### ISSUE THREAD

**Issue by amanuel2** [cloudflare-hiring/cloudflare-2020-general-engineering-assignment#1]
I keep recieving this error that I didnt install wrangler. I've tried all solutions from [here ](https://github.com/cloudflare/wrangler/issues/1479 )and [here](https://github.com/cloudflare/wrangler/issues/240), but none of them work. Help would be appreciated!

```
$ sudo npm install @cloudflare/wrangler -g --unsafe-perm=true --allow-root
/usr/local/bin/wrangler -> /usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js

> @cloudflare/wrangler@1.11.0 postinstall /usr/local/lib/node_modules/@cloudflare/wrangler
> node ./install-wrangler.js

Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.11.0/x86_64-unknown-linux-musl
wrangler has been installed!
+ @cloudflare/wrangler@1.11.0
added 34 packages from 21 contributors in 4.462s
$ wrangler --help

/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/binary-install/src/binary.js:60
      throw `You have not installed ${this.name ? this.name : "this package"}`;
      ^
You have not installed wrangler
(Use `node --trace-uncaught ...` to show where the exception was thrown)
$ 
```

**Comment by kalpaj12** [comment]
Hi @amanuel2,

The following steps helped me fix this issue.

1) Install [yarn](https://yarnpkg.com/getting-started/install/)
2) use the command `yarn global add @cloudflare/wrangler`, to install wrangler globally
3) Finally, to check if wrangler was successfully installed, run `wrangler --version`

Whose output should be `wrangler 1.11.0` .

You now have wrangler installed, and can go ahead with the assignment! :)
