### ISSUE TITLE
Unable to submit on Greenhouse

### ISSUE THREAD

**Issue by charlescqian** [cloudflare-hiring/cloudflare-2020-general-engineering-assignment#8]
Hi, I've been trying to attach my work to the Greenhouse link for the past week but I get the following error whenever I try to attach my zip files: 
`cf-assignment-worker.zip failed to upload: Could not contact request signing server. Status = 500`

I've tried contacting the recruiting team but I haven't gotten a response, so I thought to try here. Thank you for your help!

**Comment by esilverm** [comment]
Another email was sent with an updated submission link. Try searching your inbox with the text `Cloudflare: NEW LINK`

**Comment by charlescqian** [comment]
Wow, that got lost in my emails. Thank you so much!!
